[tox]
envlist = py310, py311, py312, py313, py314
isolated_build = true

[testenv]
allowlist_externals = poetry
commands_pre =
    poetry install --no-interaction
commands =
    poetry run pytest --capture=sys \
        --junit-xml=coverage/test-results.xml \
        --cov=terminalizer2asciinema \
        --cov-report term-missing \
        --cov-report xml:coverage/coverage.xml \
        --cov-report html:coverage/coverage.html \
        --cov-report lcov:coverage/coverage.info
